AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple rest api.
Resources:
  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/get-all-user-func
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /user
            Method: get
      Environment:
        Variables:
          PG_CONNECTION: "PG_CONNECTION_URL"
  GetUserByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/get-user-by-id-func
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /user/{userid}
            Method: get
      Environment:
        Variables:
          PG_CONNECTION: "PG_CONNECTION_URL"
